### ISSUE TITLE
App load time delay

### ISSUE THREAD

**Issue by BolajiAyodeji** [pwafire/pwafire#36]
**PWA installed properly**
#### But i noticed my site load speed reduce?
Any comments @mayeedwin ?

**Comment by mayeedwin** [comment]
Hey @BolajiAyodeji , it shouldn't affect your site's speed. But all is not lost. We have an awesome pwa audit tool by Google Developers that will help you know what to fix ; Go to [Lighthouse here](https://developers.google.com/web/tools/lighthouse/)

I am going to leave this issue open just to allow for follow up . Cheers.

**Comment by BolajiAyodeji** [comment]
Alright, thanks @mayeedwin.
*Would check that*

**Comment by mayeedwin** [comment]
I will close this issue now, feel free to re-issue in case you face any problems. Lighthouse will guide.
