### ISSUE TITLE
Not working on Github Pages Host

### ISSUE THREAD

**Issue by BolajiAyodeji** [pwafire/pwafire#37]
PWA prompt not notifying

**Comment by mayeedwin** [comment]
not @pwafire #bundle problem, it's a github pages issue.

**Comment by BolajiAyodeji** [comment]
Alright @mayeedwin

**Comment by mayeedwin** [comment]
It's working super cool and as a desktop [progressive web app ](https://pwafire.org/developer/docs/how-to-install-desktop-pwa/)as well.
