### ISSUE TITLE
Files not Working Offline | PHP Build

### ISSUE THREAD

**Issue by BolajiAyodeji** [pwafire/pwafire#40]
**Describe the bug**
I was working on a PHP project with file path `/index.php` and includes `/includes/header.php`
Installed service worker in `index.php` before closing body.
PWA works fine and Installs on Mobile and Desktop.
But I ran Light House audits check and discovered that the app does not work Offline.
Seem my ` return cache.addAll([` is not catching php files?
What could be wrong?

**Expected behavior**
PWA should work Offline

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] [ x ]

**Smartphone (please complete the following information):**

**Comment by BolajiAyodeji** [comment]
@mayeedwin

**Comment by mayeedwin** [comment]
Kind;y share the url to your site if live and/or screenshot

**Comment by BolajiAyodeji** [comment]
Its a company site, I can't share URL.
What screenshot do you need?

**Comment by mayeedwin** [comment]
In the console, is your service worker registered?

**Comment by BolajiAyodeji** [comment]
Yes!
It works perfectly and I can add to Home screen

**Comment by BolajiAyodeji** [comment]
This is what my caching looks like
![image](https://user-images.githubusercontent.com/30334776/49086164-2400b180-f254-11e8-83d4-3f1f6e337c57.png)

**Comment by BolajiAyodeji** [comment]
Is there a new release of PWAFire's version of Service Worker?

**Comment by mayeedwin** [comment]
Not yet. Is it working offline when you go plane mode or disconnected?

**Comment by BolajiAyodeji** [comment]
No it doesn't
`https://upnepa-web.herokuapp.com/index.php?launcher=true`

**Comment by BolajiAyodeji** [comment]
No It doesn't

**Comment by mayeedwin** [comment]
Is the `service-worker.js` in the root folder? And have you made sure that its src url is well config in the index page?

**Comment by mayeedwin** [comment]
Now make this change from the codeblock below;


```
<script>
      if ('serviceWorker' in navigator)
      {
      window.addEventListener('load', function() {
      	navigator.serviceWorker.register('/src/service-worker.js')
      	.then(function() { console.log("Service Worker Registered! | Upnepa Nigeria"); });
      });
      }

    </script>
```


to this one below;
```


<script>
      if ('serviceWorker' in navigator)
      {
      window.addEventListener('load', function() {
      	navigator.serviceWorker.register('/service-worker.js')
      	.then(function() { console.log("Service Worker Registered! | Upnepa Nigeria"); });
      });
      }

    </script>
```


Make sure `service-worker.js` is in the root folder. So that means the index file of your web app is in the **src** folder which should be your root folder.

**Comment by BolajiAyodeji** [comment]
Oh, it won't cache if its not in root?
The  src url is well config in the index page

**Comment by mayeedwin** [comment]
Should be as shown above : )

**Comment by BolajiAyodeji** [comment]
`Uncaught (in promise) TypeError: Failed to fetch`

**Comment by BolajiAyodeji** [comment]
Its not prompting Installation anymore!
`[ServiceWorker] Install
(index):496
Service Worker Registered! 
service-worker.js:68
 [ServiceWorker] Caching app shell
`

**Comment by BolajiAyodeji** [comment]
I think this is happening because its .php
.html works fine

**Comment by mayeedwin** [comment]
Interesting, I'll keep this issue open. If the index page is in the root folder with the service worker file then you'll have to register the service worker as shown earlier. That should work just perfectly fine.

**Comment by BolajiAyodeji** [comment]
Okay, I reverted to my last commit and moved the service worker installation code to head.
Now service worker installs and I can add to home screen, but it still doesn't work offline?
How do I fix?

**Comment by BolajiAyodeji** [comment]
Files not catching for Offline mode?
@mayeedwin

**Comment by BolajiAyodeji** [comment]
This is the error i get in console when i try to view offline.
service-worker.js:28 
`Uncaught (in promise) TypeError: event.waitUntil is not a function`
    at service-worker.js:28
(anonymous) @ service-worker.js:28
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
An unknown error occurred when fetching the script.
Failed to load resource: net::ERR_INTERNET_DISCONNECTED

**Comment by mayeedwin** [comment]
> Okay, I reverted to my last commit and moved the service worker installation code to head.
> Now service worker installs and I can add to home screen, but it still doesn't work offline?
> How do I fix?

I just did the audit on it, it's working offline !

**Comment by mayeedwin** [comment]
> T

It's a common error, nothing affected really by this error, meanwhile, ignore it

**Comment by mayeedwin** [comment]
> Uncaught (in promise) TypeError: event.waitUntil is not a function

A normal error. Doe not have any adverse effect. Ignore it meanwhile : )

**Comment by BolajiAyodeji** [comment]
> > Uncaught (in promise) TypeError: event.waitUntil is not a function
> 
> A normal error. Doe not have any adverse effect. Ignore it meanwhile : )

Okay!
But it still does not work Offline?
Why?

**Comment by mayeedwin** [comment]
> Okay!
> But it still does not work Offline?
> Why?

Could you just uninstall it and reinstall it? or clear your cache?
It's up!

**Comment by BolajiAyodeji** [comment]
Let me try

**Comment by BolajiAyodeji** [comment]
> > Okay!
> > But it still does not work Offline?
> > Why?
> 
> Could you just uninstall it and reinstall it? or clear your cache?
> It's up!

It still does not work
`This site can’t be reached`

**Comment by BolajiAyodeji** [comment]
@mayeedwin Its not working Offline :disappointed:

**Comment by mayeedwin** [comment]
What exactly have you done among the above? The web app works so perfectly offline on my machine and even installs on desktop

Just uninstall it and clear your cache ; re install the app

![screenshot 38](https://user-images.githubusercontent.com/17247358/49115371-aec0cb00-f2ab-11e8-90d8-aab739d0a1d4.png)

**Comment by BolajiAyodeji** [comment]
I uninstalled and cleared caches?

**Comment by BolajiAyodeji** [comment]
Can you send a screenshot of the console while triggering Offline mode, Chrome Dev Tools?

**Comment by BolajiAyodeji** [comment]
You viewing on Mobile or Desktop?

**Comment by mayeedwin** [comment]
> Can you send a screenshot of the console while triggering Offline mode, Chrome Dev Tools?

It's working just make sure that you do as above.

 
![screenshow](https://user-images.githubusercontent.com/17247358/49115298-7faa5980-f2ab-11e8-9294-c4e45d4e4cef.jpg)

**Comment by BolajiAyodeji** [comment]
Okay!
But the last time I ran LightHouse audits, I got errors of not working Offline on PWA and i tested myself tho.
Let me clear cache again and run audits!
Would get back to you.

**Comment by BolajiAyodeji** [comment]
Okay!
Its working Offline now!
Is there a way to setup some timing for caching?
Like
` Cache-Control: max-age=86400`
