### ISSUE TITLE
Spelling Typos

### ISSUE THREAD

**Issue by ghost** [pwafire/pwafire#50]
Referring to URL => https://pwafire.org/developer/codelabs/pwafire/

Web Manifest // app.webmanifest config section:
Typo => ( call it **aything** you want)

Firebase Hosting section:
Incorrect term => Para 6. are in the **PWA Fire Profile** directory then

Result did not occur => 10. Visit your web app on your phone now. You should see an "install to homescreen" banner  There was no 'install to homescreen' message or icon

**Comment by mayeedwin** [comment]
✅ typo fix
✅ dir fix
✅ install depends on the browser // usually takes some time as the user interacts with your PWA
