### ISSUE TITLE
Mac OSX Menu of app has "<start/>" instead of AppName

### ISSUE THREAD

**Issue by camillo777** [pwafire/pwafire#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS SIerra 10.12.6

**Smartphone (please complete the following information):**

**Additional context**
<img width="248" alt="Screen Shot 2019-08-29 at 19 45 16" src="https://user-images.githubusercontent.com/4798456/63963682-d5f43500-ca95-11e9-82dd-af2e484fedc3.png">

**Comment by mayeedwin** [comment]
Thanks for filling that @camillo777,  that's apparently the name but will be happy to rename it to a more clear one to fix the confusion. Thank you once more!

**Comment by mayeedwin** [comment]
fixed!
