### ISSUE TITLE
Push Notifications Add

### ISSUE THREAD

**Issue by mayeedwin** [pwafire/pwafire#7]
> Enhancement of the PWA Fire bundle with *push notification*  add on by @mayeedwin to be published soon.

**Comment by obaviet** [comment]
good jos!
i hope you soon build ui automatic pwa

**Comment by mayeedwin** [comment]
Thank You! That is on course, check here https://pwafire.org

<https://pwafire.org/>

 Google Developer Community
<https://developers.google.com/programs/community/gdg/> |  LinkedIn
<https://www.linkedin.com/in/mayeedwin/> | PWA Fire
<https://pwafire.org> | Microsoft
Interns 4Afrika Graduate
<https://www.microsoft.com/africa/4afrika/interns4afrika/>

**Comment by mayeedwin** [comment]
It is done! [ Web Manifest Generator ](https://pwafire.org/developer/tools/get-manifest/)

**Comment by attaradev** [comment]
@mayeedwin Do you mind I take this up?

**Comment by mayeedwin** [comment]
Take it up! That will be great

**Comment by attaradev** [comment]
Alright.  I will work on it

**Comment by mayeedwin** [comment]
Look at the bundle directory to get a glimpse of how you should be implement the add on ( feel fee to reach out to me or @martaWpl for any further help or if you have any related questions ) Cheers !
